spring:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smth:
          auth: true
        smtp:
          starttls:
            enable: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


# GitHub Login
  security:
      oauth2:
        client:
          registration:
            github:
              client-id: ${GITHUB_CLIENT_ID}
              client-secret: ${GITHUB_CLIENT_SECRET}
  #spring.security.oauth2.client.registration.github.scope=email, public_profile

  logging:
    level.org.springframework.security=TRACE

  #TelegrammBot
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  chatId: ${BOT_CHAT_ID}
