spring:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


# GitHub Login
  security:
      oauth2:
        client:
          registration:
            github:
              client-id: ${GITHUB_CLIENT_ID}
              client-secret: ${GITHUB_CLIENT_SECRET}
  #spring.security.oauth2.client.registration.github.scope=email, public_profile

  logging:
    level.org.springframework.security=TRACE

